Repository parallaxsecond/parsec-client-rust, pull requests merged in 2020-10, with the labels that each got.

#50 Update the socket path to new location
  src/core/basic_client.rs
  src/core/ipc_handler/unix_socket.rs
Labels: invalid

#56 Remove filesystem checks
  Cargo.toml
  README.md
  src/core/ipc_handler/unix_socket.rs
  src/error.rs
Labels: enhancement

#57 Add Unix Peer Credential auth support
  src/auth.rs
  src/core/testing/core_tests.rs
Labels: enhancement, multitenancy

#58 Implement provider and auth bootstrapping
  src/auth.rs
  src/core/basic_client.rs
  src/core/operation_client.rs
  src/core/testing/core_tests.rs
  src/core/testing/mod.rs
  src/error.rs
Labels: enhancement, multitenancy

#60 Add changelog file
  CHANGELOG.md
Labels: enhancement
